website/models.py
from . import db, admin
from flask_login import UserMixin
from sqlalchemy.sql import func
from flask_admin.contrib.sqla import ModelView
#func is here used to get date from datetime


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)  # no other use can have same email
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    orders = db.relationship('Order', back_populates='user')


class Item(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    description = db.Column(db.String(250))
    size = db.Column(db.String(5))
    price = db.Column(db.Float)
    img = db.Column(db.String(150))
    orders = db.relationship('Order', back_populates='item')


class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    item_id = db.Column(db.Integer, db.ForeignKey('item.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User', back_populates='orders')
    item = db.relationship('Item', back_populates='orders')


class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    item_id = db.Column(db.Integer, db.ForeignKey('item.id'), nullable=False)
    quantity = db.Column(db.Integer, nullable=False, default=1)
    created_at = db.Column(db.DateTime(timezone=True), server_default=func.now())


admin.add_view(ModelView(User, db.session))
admin.add_view(ModelView(Item, db.session))
admin.add_view(ModelView(Order, db.session))

website/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_admin import Admin
db = SQLAlchemy()
admin = Admin()

DB_NAME = "website\\instance\\database.db"
BASE_DIR = os.path.abspath(os.path.dirname(__name__))

DB_FULL_PATH = os.path.join(BASE_DIR, DB_NAME)


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'YOLO PASSWORD KEY  xxx'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_FULL_PATH}'
    app.config['SQLALCHEMY_ECHO'] = True
    db.init_app(app)
    admin.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Item

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    return app

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db        ##means from __init__.py import db
from flask_login import login_user, logout_user, login_required, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()

        if user:
            if check_password_hash(user.password, password):
                flash("Login successful", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash("Login failed, bad password, try again", category='error')
        elif email.strip() == "":
            flash("Please enter your email address to Login", category='error')
        else:
            flash("Login failed, this email is not existing", category='error')

        return redirect(url_for('auth.login'))
    return render_template('login.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign_up', methods=["GET", "POST"])
def sign_up():
    if request.method == "POST":
        email = request.form.get('email')
        first_name = request.form.get('first_name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        user = User.query.filter_by(email=email).first()
        if user:
            flash("This email is already registered", category='error')
        elif len(email) < 4:
            flash("Email must be at least 4 characters long", category='error')
        elif len(password1) < 2:
            flash("Password must be at least 2 characters long", category='error')
        elif password1 != password2:
            flash("Passwords do not match", category='error')
        elif len(password1) < 7:
            flash("Password must be at least 7 characters long", category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()

            login_user(new_user, remember=True)

            flash("Sign up successful", category='success')
            return redirect(url_for('views.home'))

    return render_template('sign_up.html', user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import User, Item, Cart
from . import db


views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        name = request.form.get('name')
        description = request.form.get('description')
        size = request.form.get('size')
        price = float(request.form.get('price'))

        new_item = Item(name=name, description=description, size=size, price=price)
        db.session.add(new_item)
        db.session.commit()

        flash('Przedmiot został dodany!', category='success')

    return render_template('home.html')


@views.route('/show_items')
def show_items():
    items = Item.query.all()  # Pobieramy wszystkie przedmioty z bazy danych
    return render_template('show_items.html', items=items)  # Przekazujemy je do szablonu


@views.route('/delete_item/<int:item_id>', methods=['POST'])
def delete_item(item_id):
    item_to_delete = Item.query.get_or_404(item_id)
    db.session.delete(item_to_delete)
    db.session.commit()
    flash('Przedmiot został usunięty!', category='success')
    return render_template('show_items.html')


@views.route('/show_users')
def show_users():
    users = User.query.all()
    return render_template('show_users.html', users=users)


@views.route('/cart', methods=['GET', 'POST'])
@login_required
def cart():
    items = Item.query.all()  # Pobieramy wszystkie przedmioty z bazy danych

    if request.method == 'POST':
        item_id = request.form.get('item_id')
        quantity = request.form.get('quantity', type=int)
        existing_item = Cart.query.filter_by(user_id=current_user.id, item_id=item_id).first()

        if existing_item:
            existing_item.quantity += quantity
        else:
            new_cart_item = Cart(user_id=current_user.id, item_id=item_id, quantity=quantity)
            db.session.add(new_cart_item)

        db.session.commit()
        flash('Item updated in cart', category='success')

    cart_items_in_cart = Cart.query.filter_by(user_id=current_user.id).all()  # Pobieramy elementy, które są już w koszyku

    cart_items = []
    for cart_item in cart_items_in_cart:
        item = Item.query.get(cart_item.item_id)  # Zauważ zmienioną linię. Zamiast 'id', teraz jest 'item_id'.
        cart_items.append({
            'id': item.id,
            'name': item.name,
            'price': item.price,
            'size': item.size,
            'quantity': cart_item.quantity
        })

    return render_template('cart.html', cart_items=cart_items, items=items, current_user=current_user)  # Przekazujemy 'cart_items', a nie 'cart_items_in_cart'.

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

      <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

       <title>{% block title %}Home{% endblock %}</title>
    </head>

    <body>
         <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbar"
          >
            <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
              <a class="nav-item nav-link" id="home" href="/">Home</a>
              <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
              <a class="nav-item nav-link" id="login" href="/login">Login</a>
              <a class="nav-item nav-link" id="sign_up" href="/sign_up">Sign Up</a>
              <a class="nav-item nav-link" id="list_of_items" href="/show_items">List_of_items</a>
            <a class="nav-item nav-link" id="cart" href="/cart">Cart</a>
        </div>

        <div class="navbar-nav ml-auto nav-vertical-container">
          <div class="nav-vertical">
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
            <a class="nav-item nav-link" id="sign_up" href="/sign_up">Sign Up</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          </div>
          <div class="logo-container">
              <a href="/sign_up">
                <img src="{{ url_for('static', filename='logo999.png') }}" alt="Logo" id="rainbow_logo" style="height: 100px;">
              </a>
          </div>
        </div>
      </div>
    </nav>

      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
          {% if category == "error" %}
              <div class="alert alert-danger alert-dismissable fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              {% else %}
              <div class="alert alert-success alert-dismissable fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
          {% endif %}
          {% endfor %}
      {% endif %}
      {% endwith %}

      <div class="container">
          {% block content %}dupa urbana{% endblock %}
      </div>



       <script
          src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossorigin="anonymous"
        ></script>

    </body>
</html>

website/templates/cart.html
{% extends "base.html" %}
{% block title %}List of Items{% endblock %}


{% block content %}
{{ current_user.id }} <br>
{{ current_user.email }} <br>
<br>


<form method="post">
    <select name="item_id">
      {% for item in items %}
        <option value="{{ item.id }}">
          {{ item.name }} - {{ item.size }} - {{ item.price }} zł
        </option>
      {% endfor %}
    </select>
    <input type="number" name="quantity" value="1">
    <button type="submit">Add to Cart</button>
</form>

<br><br>
<h3>Your cart List, dear {{ current_user.email }}</h3>

<ul>
  {% for item in cart_items %}
    <li>
      {{ item['name'] }}, {{ item['price'] }} zł, {{ item['size'] }}, Ilość: {{ item.quantity }}
    </li>
  {% endfor %}
</ul>


{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}My New Home ALABAMA <3{% endblock %}

{% block content %}

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
<title>{% block title %}Login{% endblock %}</title>

{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Adress</label>
        <input
                type="email"
                class="form-control"
                id="email"
                name="email"
                placeholder="Enter email"
        />
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input
                type="passowrd"
                class="form-control"
                id="password"
                name="password"
                placeholder="Enter password"
        />
    </div>

    <br>
    <button type="submit" class="btn btn-primary">Login</button>

</form>
{% endblock %}

website/templates/show_items.html
{% extends "base.html" %}
{% block title %}List of Items{% endblock %}



{% block content %}

  <h1>Lista przedmiotów</h1>
  <div class="items-grid">
    {% for item in items %}
      <div class="item">
        <img src="{{ url_for('static', filename=item.img) }}" alt="Opis zdjęcia">
        <p>Id: {{ item.id }}, Nazwa: {{ item.name }}</p>
        <p>Opis: {{ item.description }}</p>
        <p>Rozmiar: {{ item.size }}, Cena: {{ item.price }} zł</p>
        <form action="{{ url_for('views.delete_item', item_id=item.id) }}" method="post">
          <button type="submit">Usuń</button>
        </form>
      </div>
    {% endfor %}
  </div>

{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
<title>{% block title %}Sign Up{% endblock %}</title>
{% block content %}
<form method="POST">
    <h3 align="center">Sign UP</h3>
    <div class="form-group">
        <label for="email">Email Adress</label>
        <input
                type="email"
                class="form-control"
                id="email"
                name="email"
                placeholder="Enter email"
        />
    </div>

    <div class="form-group">
        <label for="first_name">First Name</label>
        <input
                type="text"
                class="form-control"
                id="first_name"
                name="first_name"
                placeholder="Enter first name"
        />
    </div>

    <div class="form-group">
        <label for="password1">Password</label>
        <input
                type="passowrd"
                class="form-control"
                id="password1"
                name="password1"
                placeholder="Enter password"
        />
    </div>

    <div class="form-group">
        <label for="password2">Repeat Password</label>
        <input
                type="passowrd"
                class="form-control"
                id="password2"
                name="password2"
                placeholder="Confirm password"
        />
    </div>

    <br>
    <button type="submit" class="btn btn-primary">Submit</button>

</form>
{% endblock %}